#version 460 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(r32f, binding = 0) uniform image2D matrix;
layout(r32f, binding = 1) uniform image1D vector;
layout(r32f, binding = 2) uniform image1D result;

void main() {
    float value = 0.0f;
	for(int i = 0; i < gl_NumWorkGroups.x; i++) {
        value += imageLoad(matrix, ivec2(i, gl_WorkGroupID.x)).r * imageLoad(vector, i).r;
    }
    imageStore(result, int(gl_WorkGroupID.x), vec4(value, 0.0f, 0.0f, 0.0f));
}